In [36]:
import requests

url = "https://api.openf1.org/v1/sessions"

params = {
    "year": 2026,
    "session_name": "Race",
}

response = requests.get(url, params=params)
response.raise_for_status()

data = response.json()

print(data)

[{'session_key': 11234, 'session_type': 'Race', 'session_name': 'Race', 'date_start': '2026-03-08T04:00:00+00:00', 'date_end': '2026-03-08T06:00:00+00:00', 'meeting_key': 1279, 'circuit_key': 10, 'circuit_short_name': 'Melbourne', 'country_key': 5, 'country_code': 'AUS', 'country_name': 'Australia', 'location': 'Melbourne', 'gmt_offset': '11:00:00', 'year': 2026, 'is_cancelled': False}, {'session_key': 11245, 'session_type': 'Race', 'session_name': 'Race', 'date_start': '2026-03-15T07:00:00+00:00', 'date_end': '2026-03-15T09:00:00+00:00', 'meeting_key': 1280, 'circuit_key': 49, 'circuit_short_name': 'Shanghai', 'country_key': 53, 'country_code': 'CHN', 'country_name': 'China', 'location': 'Shanghai', 'gmt_offset': '08:00:00', 'year': 2026, 'is_cancelled': False}, {'session_key': 11253, 'session_type': 'Race', 'session_name': 'Race', 'date_start': '2026-03-29T05:00:00+00:00', 'date_end': '2026-03-29T07:00:00+00:00', 'meeting_key': 1281, 'circuit_key': 46, 'circuit_short_name': 'Suzuka', 'country_key': 4, 'country_code': 'JPN', 'country_name': 'Japan', 'location': 'Suzuka', 'gmt_offset': '09:00:00', 'year': 2026, 'is_cancelled': False}, {'session_key': 11261, 'session_type': 'Race', 'session_name': 'Race', 'date_start': '2026-04-12T15:00:00+00:00', 'date_end': '2026-04-12T17:00:00+00:00', 'meeting_key': 1282, 'circuit_key': 63, 'circuit_short_name': 'Sakhir', 'country_key': 36, 'country_code': 'BRN', 'country_name': 'Bahrain', 'location': 'Sakhir', 'gmt_offset': '03:00:00', 'year': 2026, 'is_cancelled': True}, {'session_key': 11269, 'session_type': 'Race', 'session_name': 'Race', 'date_start': '2026-04-19T17:00:00+00:00', 'date_end': '2026-04-19T19:00:00+00:00', 'meeting_key': 1283, 'circuit_key': 149, 'circuit_short_name': 'Jeddah', 'country_key': 153, 'country_code': 'KSA', 'country_name': 'Saudi Arabia', 'location': 'Jeddah', 'gmt_offset': '03:00:00', 'year': 2026, 'is_cancelled': True}, {'session_key': 11280, 'session_type': 'Race', 'session_name': 'Race', 'date_start': '2026-05-03T17:00:00+00:00', 'date_end': '2026-05-03T19:00:00+00:00', 'meeting_key': 1284, 'circuit_key': 151, 'circuit_short_name': 'Miami', 'country_key': 19, 'country_code': 'USA', 'country_name': 'United States', 'location': 'Miami Gardens', 'gmt_offset': '-04:00:00', 'year': 2026, 'is_cancelled': False}, {'session_key': 11291, 'session_type': 'Race', 'session_name': 'Race', 'date_start': '2026-05-24T20:00:00+00:00', 'date_end': '2026-05-24T22:00:00+00:00', 'meeting_key': 1285, 'circuit_key': 23, 'circuit_short_name': 'Montreal', 'country_key': 46, 'country_code': 'CAN', 'country_name': 'Canada', 'location': 'Montréal', 'gmt_offset': '-04:00:00', 'year': 2026, 'is_cancelled': False}, {'session_key': 11299, 'session_type': 'Race', 'session_name': 'Race', 'date_start': '2026-06-07T13:00:00+00:00', 'date_end': '2026-06-07T15:00:00+00:00', 'meeting_key': 1286, 'circuit_key': 22, 'circuit_short_name': 'Monte Carlo', 'country_key': 114, 'country_code': 'MON', 'country_name': 'Monaco', 'location': 'Monte Carlo', 'gmt_offset': '02:00:00', 'year': 2026, 'is_cancelled': False}, {'session_key': 11307, 'session_type': 'Race', 'session_name': 'Race', 'date_start': '2026-06-14T13:00:00+00:00', 'date_end': '2026-06-14T15:00:00+00:00', 'meeting_key': 1287, 'circuit_key': 15, 'circuit_short_name': 'Catalunya', 'country_key': 1, 'country_code': 'ESP', 'country_name': 'Spain', 'location': 'Barcelona', 'gmt_offset': '02:00:00', 'year': 2026, 'is_cancelled': False}, {'session_key': 11315, 'session_type': 'Race', 'session_name': 'Race', 'date_start': '2026-06-28T13:00:00+00:00', 'date_end': '2026-06-28T15:00:00+00:00', 'meeting_key': 1288, 'circuit_key': 19, 'circuit_short_name': 'Spielberg', 'country_key': 17, 'country_code': 'AUT', 'country_name': 'Austria', 'location': 'Spielberg', 'gmt_offset': '02:00:00', 'year': 2026, 'is_cancelled': False}, {'session_key': 11326, 'session_type': 'Race', 'session_name': 'Race', 'date_start': '2026-07-05T14:00:00+00:00', 'date_end': '2026-07-05T16:00:00+00:00', 'meeting_key': 1289, 'circuit_key': 2, 'circuit_short_name': 'Silverstone', 'country_key': 2, 'country_code': 'GBR', 'country_name': 'United Kingdom', 'location': 'Silverstone', 'gmt_offset': '01:00:00', 'year': 2026, 'is_cancelled': False}, {'session_key': 11334, 'session_type': 'Race', 'session_name': 'Race', 'date_start': '2026-07-19T13:00:00+00:00', 'date_end': '2026-07-19T15:00:00+00:00', 'meeting_key': 1290, 'circuit_key': 7, 'circuit_short_name': 'Spa-Francorchamps', 'country_key': 16, 'country_code': 'BEL', 'country_name': 'Belgium', 'location': 'Spa-Francorchamps', 'gmt_offset': '02:00:00', 'year': 2026, 'is_cancelled': False}, {'session_key': 11342, 'session_type': 'Race', 'session_name': 'Race', 'date_start': '2026-07-26T13:00:00+00:00', 'date_end': '2026-07-26T15:00:00+00:00', 'meeting_key': 1291, 'circuit_key': 4, 'circuit_short_name': 'Hungaroring', 'country_key': 14, 'country_code': 'HUN', 'country_name': 'Hungary', 'location': 'Budapest', 'gmt_offset': '02:00:00', 'year': 2026, 'is_cancelled': False}, {'session_key': 11353, 'session_type': 'Race', 'session_name': 'Race', 'date_start': '2026-08-23T13:00:00+00:00', 'date_end': '2026-08-23T15:00:00+00:00', 'meeting_key': 1292, 'circuit_key': 55, 'circuit_short_name': 'Zandvoort', 'country_key': 133, 'country_code': 'NED', 'country_name': 'Netherlands', 'location': 'Zandvoort', 'gmt_offset': '02:00:00', 'year': 2026, 'is_cancelled': False}, {'session_key': 11361, 'session_type': 'Race', 'session_name': 'Race', 'date_start': '2026-09-06T13:00:00+00:00', 'date_end': '2026-09-06T15:00:00+00:00', 'meeting_key': 1293, 'circuit_key': 39, 'circuit_short_name': 'Monza', 'country_key': 13, 'country_code': 'ITA', 'country_name': 'Italy', 'location': 'Monza', 'gmt_offset': '02:00:00', 'year': 2026, 'is_cancelled': False}, {'session_key': 11369, 'session_type': 'Race', 'session_name': 'Race', 'date_start': '2026-09-13T13:00:00+00:00', 'date_end': '2026-09-13T15:00:00+00:00', 'meeting_key': 1294, 'circuit_key': 153, 'circuit_short_name': 'Madring', 'country_key': 1, 'country_code': 'ESP', 'country_name': 'Spain', 'location': 'Madrid', 'gmt_offset': '02:00:00', 'year': 2026, 'is_cancelled': False}, {'session_key': 11377, 'session_type': 'Race', 'session_name': 'Race', 'date_start': '2026-09-26T11:00:00+00:00', 'date_end': '2026-09-26T13:00:00+00:00', 'meeting_key': 1295, 'circuit_key': 144, 'circuit_short_name': 'Baku', 'country_key': 30, 'country_code': 'AZE', 'country_name': 'Azerbaijan', 'location': 'Baku', 'gmt_offset': '04:00:00', 'year': 2026, 'is_cancelled': False}, {'session_key': 11731, 'session_type': 'Race', 'session_name': 'Race', 'date_start': '2026-10-04T07:00:00+00:00', 'date_end': '2026-10-04T09:00:00+00:00', 'meeting_key': 1308, 'circuit_key': 12, 'circuit_short_name': 'Kuala Lumpur', 'country_key': 36, 'country_code': 'BRN', 'country_name': 'Bahrain', 'location': 'Kuala Lumpur', 'gmt_offset': '08:00:00', 'year': 2026, 'is_cancelled': False}, {'session_key': 11388, 'session_type': 'Race', 'session_name': 'Race', 'date_start': '2026-10-11T12:00:00+00:00', 'date_end': '2026-10-11T14:00:00+00:00', 'meeting_key': 1296, 'circuit_key': 61, 'circuit_short_name': 'Singapore', 'country_key': 157, 'country_code': 'SGP', 'country_name': 'Singapore', 'location': 'Marina Bay', 'gmt_offset': '08:00:00', 'year': 2026, 'is_cancelled': False}, {'session_key': 11396, 'session_type': 'Race', 'session_name': 'Race', 'date_start': '2026-10-25T20:00:00+00:00', 'date_end': '2026-10-25T22:00:00+00:00', 'meeting_key': 1297, 'circuit_key': 9, 'circuit_short_name': 'Austin', 'country_key': 19, 'country_code': 'USA', 'country_name': 'United States', 'location': 'Austin', 'gmt_offset': '-05:00:00', 'year': 2026, 'is_cancelled': False}, {'session_key': 11404, 'session_type': 'Race', 'session_name': 'Race', 'date_start': '2026-11-01T20:00:00+00:00', 'date_end': '2026-11-01T22:00:00+00:00', 'meeting_key': 1298, 'circuit_key': 65, 'circuit_short_name': 'Mexico City', 'country_key': 8, 'country_code': 'MEX', 'country_name': 'Mexico', 'location': 'Mexico City', 'gmt_offset': '-06:00:00', 'year': 2026, 'is_cancelled': False}, {'session_key': 11412, 'session_type': 'Race', 'session_name': 'Race', 'date_start': '2026-11-08T17:00:00+00:00', 'date_end': '2026-11-08T19:00:00+00:00', 'meeting_key': 1299, 'circuit_key': 14, 'circuit_short_name': 'Interlagos', 'country_key': 10, 'country_code': 'BRA', 'country_name': 'Brazil', 'location': 'São Paulo', 'gmt_offset': '-03:00:00', 'year': 2026, 'is_cancelled': False}, {'session_key': 11420, 'session_type': 'Race', 'session_name': 'Race', 'date_start': '2026-11-22T04:00:00+00:00', 'date_end': '2026-11-22T06:00:00+00:00', 'meeting_key': 1300, 'circuit_key': 152, 'circuit_short_name': 'Las Vegas', 'country_key': 19, 'country_code': 'USA', 'country_name': 'United States', 'location': 'Las Vegas', 'gmt_offset': '-08:00:00', 'year': 2026, 'is_cancelled': False}, {'session_key': 11428, 'session_type': 'Race', 'session_name': 'Race', 'date_start': '2026-11-29T16:00:00+00:00', 'date_end': '2026-11-29T18:00:00+00:00', 'meeting_key': 1301, 'circuit_key': 150, 'circuit_short_name': 'Lusail', 'country_key': 149, 'country_code': 'QAT', 'country_name': 'Qatar', 'location': 'Lusail', 'gmt_offset': '03:00:00', 'year': 2026, 'is_cancelled': False}, {'session_key': 11436, 'session_type': 'Race', 'session_name': 'Race', 'date_start': '2026-12-06T13:00:00+00:00', 'date_end': '2026-12-06T15:00:00+00:00', 'meeting_key': 1302, 'circuit_key': 70, 'circuit_short_name': 'Yas Marina Circuit', 'country_key': 21, 'country_code': 'UAE', 'country_name': 'United Arab Emirates', 'location': 'Yas Marina', 'gmt_offset': '04:00:00', 'year': 2026, 'is_cancelled': False}]

In [37]:
import pandas as pd


races=pd.DataFrame(data)
races['date_start']=pd.to_datetime(races['date_start'])

races.head()

,session_key,session_type,session_name,date_start,date_end,meeting_key,circuit_key,circuit_short_name,country_key,country_code,country_name,location,gmt_offset,year,is_cancelled
0,11234,Race,Race,2026-03-08 04:00:00+00:00,2026-03-08T06:00:00+00:00,1279,10,Melbourne,5,AUS,Australia,Melbourne,11:00:00,2026,False
1,11245,Race,Race,2026-03-15 07:00:00+00:00,2026-03-15T09:00:00+00:00,1280,49,Shanghai,53,CHN,China,Shanghai,08:00:00,2026,False
2,11253,Race,Race,2026-03-29 05:00:00+00:00,2026-03-29T07:00:00+00:00,1281,46,Suzuka,4,JPN,Japan,Suzuka,09:00:00,2026,False
3,11261,Race,Race,2026-04-12 15:00:00+00:00,2026-04-12T17:00:00+00:00,1282,63,Sakhir,36,BRN,Bahrain,Sakhir,03:00:00,2026,True
4,11269,Race,Race,2026-04-19 17:00:00+00:00,2026-04-19T19:00:00+00:00,1283,149,Jeddah,153,KSA,Saudi Arabia,Jeddah,03:00:00,2026,True

In [38]:
races.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   session_key         25 non-null     int64
 1   session_type        25 non-null     object
 2   session_name        25 non-null     object
 3   date_start          25 non-null     datetime64[ns, UTC]
 4   date_end            25 non-null     object
 5   meeting_key         25 non-null     int64
 6   circuit_key         25 non-null     int64
 7   circuit_short_name  25 non-null     object
 8   country_key         25 non-null     int64
 9   country_code        25 non-null     object
 10  country_name        25 non-null     object
 11  location            25 non-null     object
 12  gmt_offset          25 non-null     object
 13  year                25 non-null     int64
 14  is_cancelled        25 non-null     bool
dtypes: bool(1), datetime64[ns, UTC](1), int64(5), object(8)
memory usage: 2.9+ KB

In [39]:
import pandas as pd

now = pd.Timestamp.now(tz='UTC')
filtered = races[races['date_start'] <= now]

filtered

,session_key,session_type,session_name,date_start,date_end,meeting_key,circuit_key,circuit_short_name,country_key,country_code,country_name,location,gmt_offset,year,is_cancelled
0,11234,Race,Race,2026-03-08 04:00:00+00:00,2026-03-08T06:00:00+00:00,1279,10,Melbourne,5,AUS,Australia,Melbourne,11:00:00,2026,False
1,11245,Race,Race,2026-03-15 07:00:00+00:00,2026-03-15T09:00:00+00:00,1280,49,Shanghai,53,CHN,China,Shanghai,08:00:00,2026,False
2,11253,Race,Race,2026-03-29 05:00:00+00:00,2026-03-29T07:00:00+00:00,1281,46,Suzuka,4,JPN,Japan,Suzuka,09:00:00,2026,False
3,11261,Race,Race,2026-04-12 15:00:00+00:00,2026-04-12T17:00:00+00:00,1282,63,Sakhir,36,BRN,Bahrain,Sakhir,03:00:00,2026,True
4,11269,Race,Race,2026-04-19 17:00:00+00:00,2026-04-19T19:00:00+00:00,1283,149,Jeddah,153,KSA,Saudi Arabia,Jeddah,03:00:00,2026,True
5,11280,Race,Race,2026-05-03 17:00:00+00:00,2026-05-03T19:00:00+00:00,1284,151,Miami,19,USA,United States,Miami Gardens,-04:00:00,2026,False
6,11291,Race,Race,2026-05-24 20:00:00+00:00,2026-05-24T22:00:00+00:00,1285,23,Montreal,46,CAN,Canada,Montréal,-04:00:00,2026,False
7,11299,Race,Race,2026-06-07 13:00:00+00:00,2026-06-07T15:00:00+00:00,1286,22,Monte Carlo,114,MON,Monaco,Monte Carlo,02:00:00,2026,False
8,11307,Race,Race,2026-06-14 13:00:00+00:00,2026-06-14T15:00:00+00:00,1287,15,Catalunya,1,ESP,Spain,Barcelona,02:00:00,2026,False
9,11315,Race,Race,2026-06-28 13:00:00+00:00,2026-06-28T15:00:00+00:00,1288,19,Spielberg,17,AUT,Austria,Spielberg,02:00:00,2026,False
10,11326,Race,Race,2026-07-05 14:00:00+00:00,2026-07-05T16:00:00+00:00,1289,2,Silverstone,2,GBR,United Kingdom,Silverstone,01:00:00,2026,False
11,11334,Race,Race,2026-07-19 13:00:00+00:00,2026-07-19T15:00:00+00:00,1290,7,Spa-Francorchamps,16,BEL,Belgium,Spa-Francorchamps,02:00:00,2026,False
12,11342,Race,Race,2026-07-26 13:00:00+00:00,2026-07-26T15:00:00+00:00,1291,4,Hungaroring,14,HUN,Hungary,Budapest,02:00:00,2026,False
13,11353,Race,Race,2026-08-23 13:00:00+00:00,2026-08-23T15:00:00+00:00,1292,55,Zandvoort,133,NED,Netherlands,Zandvoort,02:00:00,2026,False
14,11361,Race,Race,2026-09-06 13:00:00+00:00,2026-09-06T15:00:00+00:00,1293,39,Monza,13,ITA,Italy,Monza,02:00:00,2026,False
15,11369,Race,Race,2026-09-13 13:00:00+00:00,2026-09-13T15:00:00+00:00,1294,153,Madring,1,ESP,Spain,Madrid,02:00:00,2026,False

In [40]:
BASE='https://api.openf1.org/v1'

sessions=requests.get(
    f'{BASE}/sessions',
    params={
        'year': 2026,
        'country_name': 'Spain',
        'session_name': 'Race'
    }
).json()


sessions_df = pd.DataFrame(sessions)

sessions_df

,session_key,session_type,session_name,date_start,date_end,meeting_key,circuit_key,circuit_short_name,country_key,country_code,country_name,location,gmt_offset,year,is_cancelled
0,11307,Race,Race,2026-06-14T13:00:00+00:00,2026-06-14T15:00:00+00:00,1287,15,Catalunya,1,ESP,Spain,Barcelona,02:00:00,2026,False
1,11369,Race,Race,2026-09-13T13:00:00+00:00,2026-09-13T15:00:00+00:00,1294,153,Madring,1,ESP,Spain,Madrid,02:00:00,2026,False

In [41]:
sessions_df

,session_key,session_type,session_name,date_start,date_end,meeting_key,circuit_key,circuit_short_name,country_key,country_code,country_name,location,gmt_offset,year,is_cancelled
0,11307,Race,Race,2026-06-14T13:00:00+00:00,2026-06-14T15:00:00+00:00,1287,15,Catalunya,1,ESP,Spain,Barcelona,02:00:00,2026,False
1,11369,Race,Race,2026-09-13T13:00:00+00:00,2026-09-13T15:00:00+00:00,1294,153,Madring,1,ESP,Spain,Madrid,02:00:00,2026,False

In [42]:
drivers = requests.get(
    f"{BASE}/drivers",
    params={
        "session_key": 11369
    }
).json()

drivers_df = pd.DataFrame(drivers)

drivers_df.head(10)

,meeting_key,session_key,driver_number,broadcast_name,full_name,name_acronym,team_name,team_colour,first_name,last_name,headshot_url,country_code
0,1294,11369,1,L NORRIS,Lando NORRIS,NOR,McLaren,F47600,Lando,Norris,https://media.formula1.com/d_driver_fallback_i...,None
1,1294,11369,3,M VERSTAPPEN,Max VERSTAPPEN,VER,Red Bull Racing,4781D7,Max,Verstappen,https://media.formula1.com/d_driver_fallback_i...,None
2,1294,11369,5,G BORTOLETO,Gabriel BORTOLETO,BOR,Audi,F50537,Gabriel,Bortoleto,https://media.formula1.com/d_driver_fallback_i...,None
3,1294,11369,10,P GASLY,Pierre GASLY,GAS,Alpine,00A1E8,Pierre,Gasly,https://media.formula1.com/d_driver_fallback_i...,None
4,1294,11369,11,S PEREZ,Sergio PEREZ,PER,Cadillac,909090,Sergio,Perez,https://media.formula1.com/d_driver_fallback_i...,None
5,1294,11369,12,K ANTONELLI,Kimi ANTONELLI,ANT,Mercedes,00D7B6,Kimi,Antonelli,https://media.formula1.com/d_driver_fallback_i...,None
6,1294,11369,14,F ALONSO,Fernando ALONSO,ALO,Aston Martin,229971,Fernando,Alonso,https://media.formula1.com/d_driver_fallback_i...,None
7,1294,11369,16,C LECLERC,Charles LECLERC,LEC,Ferrari,ED1131,Charles,Leclerc,https://media.formula1.com/d_driver_fallback_i...,None
8,1294,11369,18,L STROLL,Lance STROLL,STR,Aston Martin,229971,Lance,Stroll,https://media.formula1.com/d_driver_fallback_i...,None
9,1294,11369,22,Y TSUNODA,Yuki TSUNODA,TSU,Racing Bulls,6C98FF,Yuki,Tsunoda,None,None

In [43]:
laps = requests.get(
    f"{BASE}/laps",
    params={
        "session_key": 11369,
        "driver_number": 1,
    },
).json()

laps_df = pd.DataFrame(laps)

In [44]:
laps_df.head(10)

,meeting_key,session_key,driver_number,lap_number,date_start,duration_sector_1,duration_sector_2,duration_sector_3,i1_speed,i2_speed,is_pit_out_lap,lap_duration,segments_sector_1,segments_sector_2,segments_sector_3,st_speed
0,1294,11369,1,1,2026-09-13T13:04:04.248000+00:00,33.032,36.257,32.846,201.0,251,False,102.135,"[2048, 2049, 2049, 2049, 2049, 2049, 2049, 2049]","[2049, 2049, 2051, 2049, 2049, 2051, 2051, 2051]","[2051, 2051, 2049, 2049, 2051, 2051, 2051, 205...",298.0
1,1294,11369,1,2,2026-09-13T13:05:46.383000+00:00,30.504,35.647,33.253,218.0,247,False,99.404,"[2049, 2049, 2049, 2049, 2049, 2048, 2049, 2051]","[2051, 2051, 2051, 2049, 2049, 2048, 2048, 2048]","[2048, 2048, 2048, 2049, 2048, 2048, 2051, 204...",295.0
2,1294,11369,1,3,2026-09-13T13:07:25.754000+00:00,30.661,36.019,33.431,NaN,250,False,100.111,"[2048, 2048, 2049, 2049, 2049, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",294.0
3,1294,11369,1,4,2026-09-13T13:09:05.999000+00:00,30.370,36.213,33.536,220.0,249,False,100.119,"[None, 2049, 2049, 2048, 2048, 2048, 2048, 2051]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",287.0
4,1294,11369,1,5,2026-09-13T13:10:46.093000+00:00,30.385,36.044,33.335,218.0,250,False,99.764,"[2049, 2048, 2049, 2048, 2048, 2048, 2048, 2051]","[2048, 2048, 2048, 2048, 2049, 2051, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",291.0
5,1294,11369,1,6,2026-09-13T13:12:25.945000+00:00,30.389,35.842,33.114,223.0,252,False,99.345,"[2048, 2048, 2048, 2048, 2048, 2048, 2049, 2051]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2049, 2048, 2048, 2051, 204...",295.0
6,1294,11369,1,7,2026-09-13T13:14:05.178000+00:00,30.334,35.872,33.292,222.0,252,False,99.498,"[2049, 2048, 2048, 2048, 2049, 2048, 2049, 2048]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 2051]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",294.0
7,1294,11369,1,8,2026-09-13T13:15:44.694000+00:00,30.307,35.780,33.256,NaN,252,False,99.343,"[None, 2049, 2048, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2051, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",299.0
8,1294,11369,1,9,2026-09-13T13:17:24.045000+00:00,30.233,35.709,33.180,NaN,252,False,99.122,"[2048, 2048, 2049, 2049, 2049, 2048, 2049, 2048]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2048, 2048, 2048, 2051, 204...",296.0
9,1294,11369,1,10,2026-09-13T13:19:03.154000+00:00,30.297,35.713,33.081,220.0,253,False,99.091,"[None, 2048, 2048, 2048, 2048, 2048, 2048, 2048]","[2048, 2048, 2048, 2051, 2048, 2048, 2048, 2051]","[2048, 2048, 2048, 2048, 2048, 2048, 2048, 204...",292.0

In [ ]:
telemetry = requests.get(
    f"{BASE}/car_data",
    params={
        "session_key": 11369,
        "driver_number": 1,
    },
).json()

telemetry_df = pd.DataFrame(telemetry)

KeyboardInterrupt:

In [ ]:
telemetry_df